### ISSUE TITLE
wabt-sys cannot Compiling,help me!!

### ISSUE THREAD

**Issue by kasumisk** [dfinity/internet-identity#320] opened 2021-06-07 13:12 UTC
I have a problem after running dfx deploy --no-wallet --argument'(null)'
Operating environment:
macos big sur 11.2.3
rust 1.51
dfx 0.7.1
cmake 3.20.3

`
webpack 5.24.4 compiled with 3 warnings in 12472 ms
    Finished release [optimized] target(s) in 0.15s
    Updating crates.io index
  Installing ic-cdk-optimizer v0.3.0
   Compiling proc-macro2 v1.0.27
   Compiling libc v0.2.95
   Compiling cc v1.0.68
   Compiling unicode-xid v0.2.2
   Compiling memchr v2.4.0
   Compiling version_check v0.9.3
   Compiling syn v1.0.72
   Compiling unicode-segmentation v1.7.1
   Compiling cfg-if v1.0.0
   Compiling regex-syntax v0.6.25
   Compiling serde v1.0.126
   Compiling ryu v1.0.5
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling serde_json v1.0.64
   Compiling serde_derive v1.0.126
   Compiling ppv-lite86 v0.2.10
   Compiling itoa v0.4.7
   Compiling hashbrown v0.9.1
   Compiling unicode-width v0.1.8
   Compiling remove_dir_all v0.5.3
   Compiling termcolor v1.1.2
   Compiling strsim v0.10.0
   Compiling lazy_static v1.4.0
   Compiling vec_map v0.8.2
   Compiling os_str_bytes v2.4.0
   Compiling humansize v1.1.1
   Compiling heck v0.3.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling cmake v0.1.45
   Compiling indexmap v1.6.2
   Compiling textwrap v0.12.1
   Compiling wabt-sys v0.8.0
   Compiling quote v1.0.9
   Compiling aho-corasick v0.7.18
   Compiling getrandom v0.2.3
   Compiling atty v0.2.14
   Compiling regex v1.5.4
   Compiling rand_core v0.6.2
   Compiling rand_chacha v0.3.0
   Compiling rand v0.8.3
   Compiling tempfile v3.2.0
   Compiling binaryen-sys v0.12.0
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling wabt v0.10.0
error: failed to add native library /tmp/cargo-installyRniTi/release/build/wabt-sys-3602112ed66c1793/out/build/libwabt.a: file too small to be an archive

error: aborting due to previous error

error: could not compile `wabt-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
    Building [========================>  ] 73/77: binaryen-sys(build)                                                                                     
error: failed to compile `ic-cdk-optimizer v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installyRniTi`

Caused by:
  build failed
The build step failed for canister 'rwlgt-iiaaa-aaaaa-aaaaa-cai' with an embedded error: The custom tool failed.
`

The error reported above seems to be that wabt-sys cannot Compiling, but I cannot locate the cause by myself and cannot solve this problem.
Can anyone help me?

**Comment by nomeata** [comment] 2021-06-07 13:22
Duplicate of https://github.com/dfinity/internet-identity/issues/319

**Closed by nomeata** 2021-06-07 13:22 UTC
